#!/bin/bash

function feh_pipe()
{
for f in ${1}/*
do
	echo "<item label=\"$(basename ${f%.*})\">
	<action name=\"Execute\">
	<command>feh --bg-fill \"$f\"</command>
	</action>
	</item>"
done
}

echo "<openbox_pipe_menu>"
feh_pipe ${HOME}/Mega/Wall/Imaginism
feh_pipe ${HOME}/Mega/Wall/Burda
echo "</openbox_pipe_menu>"

